Add Docker support
LeaPhant/flowabot pull request #11
Opened 2019-07-12 15:06 UTC by LeaPhant

This implements #2.

2021-04-10 08:07 UTC, KeepSOBP requested changes

2021-04-10 08:07 UTC, KeepSOBP commented on Dockerfile
> +FROM node:10
```suggestion
FROM node:14
```
Update node image version to 14

2021-04-10 08:07 UTC, KeepSOBP commented on Dockerfile
> +    && tar zxf dotnet-sdk-2.2.301-linux-x64.tar.gz -C dotnet
```suggestion
RUN wget -q https://download.visualstudio.microsoft.com/download/pr/ab82011d-2549-4e23-a8a9-a2b522a31f27/6e615d6177e49c3e874d05ee3566e8bf/dotnet-sdk-3.1.407-linux-x64.tar.gz \
    && mkdir -p dotnet \
    && tar zxf dotnet-sdk-3.1.407-linux-x64.tar.gz -C dotnet
```
Update dotnet sdk version to 3.1.407

2021-04-10 08:07 UTC, KeepSOBP commented on Dockerfile
> +RUN bash build.sh
```suggestion
RUN dotnet build PerformanceCalculator/PerformanceCalculator.csproj
```
no build.sh file in osu-tools repo now

2021-04-10 08:07 UTC, KeepSOBP commented on Dockerfile
> +RUN jq --indent 4 '.pp_path = "/opt/osu-tools/PerformanceCalculator/bin/Release/netcoreapp2.0/PerformanceCalculator.dll"' \
```suggestion
RUN jq --indent 4 '.pp_path = "/opt/osu-tools/PerformanceCalculator/bin/Release/netcoreapp3.1/PerformanceCalculator.dll"' \
```
Update dotnet sdk version to 3.1.407

2026-06-11 15:12 UTC, LeaPhant commented
Implemented in 168a5f42b5a0fddc87a54b0253a25f2636619a4f.

2026-06-11 15:12 UTC, closed without merging